# Generated by Django 5.1.4 on 2024-12-18 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='term2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='term1',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherdetails',
            name='teacher',
        ),
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=100)),
                ('Admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.CharField(max_length=30)),
                ('subject2', models.CharField(max_length=30)),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HODDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=100)),
                ('HOD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Finals',
        ),
        migrations.DeleteModel(
            name='Term2',
        ),
        migrations.DeleteModel(
            name='StudentDetails',
        ),
        migrations.DeleteModel(
            name='Term1',
        ),
        migrations.DeleteModel(
            name='TeacherDetails',
        ),
    ]
